config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :cervezas do
    resources :pedidos
  end

  devise_for :users

  root 'cervezas#index'

end

app/models/cerveza.rb
class Cerveza < ActiveRecord::Base
	has_many :pedidos, dependent: :destroy
	has_many :users, through: :pedidos

	mount_uploader :photo_url, PhotoUploader
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
	belongs_to :cerveza
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pedidos
  has_many :cervezas, through: :pedido
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cervezas_controller.rb
class CervezasController < ApplicationController
  before_action :set_cerveza, only: [:show, :edit, :update, :destroy]
  # GET /cervezas
  # GET /cervezas.json
  def index
    @cervezas = Cerveza.all
    if user_signed_in?
      @mis_pedidos = current_user.pedidos
    end
  end

  # GET /cervezas/1
  # GET /cervezas/1.json
  def show
  end

  # GET /cervezas/new
  def new
    @cerveza = Cerveza.new
  end

  # GET /cervezas/1/edit
  def edit
  end

  # POST /cervezas
  # POST /cervezas.json
  def create
    @cerveza = Cerveza.new(cerveza_params)

    respond_to do |format|
      if @cerveza.save
        format.html { redirect_to @cerveza, notice: 'Cerveza was successfully created.' }
        format.json { render :show, status: :created, location: @cerveza }
      else
        format.html { render :new }
        format.json { render json: @cerveza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cervezas/1
  # PATCH/PUT /cervezas/1.json
  def update
    respond_to do |format|
      if @cerveza.update(cerveza_params)
        format.html { redirect_to @cerveza, notice: 'Cerveza was successfully updated.' }
        format.json { render :show, status: :ok, location: @cerveza }
      else
        format.html { render :edit }
        format.json { render json: @cerveza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cervezas/1
  # DELETE /cervezas/1.json
  def destroy
    @cerveza.destroy
    respond_to do |format|
      format.html { redirect_to cervezas_url, notice: 'Cerveza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cerveza
      @cerveza = Cerveza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cerveza_params
      params.require(:cerveza).permit(:nombre, :tipo, :photo_url)
    end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  def new
    @cerveza = Cerveza.find(params[:cerveza_id])
    Pedido.create(cerveza:@cerveza, user:current_user)
    redirect_to cervezas_path
  end

  def destroy
    @pedido = Pedido.find(params[:id])
    @pedido.destroy
    redirect_to cervezas_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cervezas_helper.rb
module CervezasHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cervezas/_form.html.erb
<%= form_for(@cerveza) do |f| %>
  <% if @cerveza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cerveza.errors.count, "error") %> prohibited this cerveza from being saved:</h2>

      <ul>
      <% @cerveza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :photo_url %><br>
    <%= f.file_field :photo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cervezas/edit.html.erb
<h1>Editing Cerveza</h1>

<%= render 'form' %>

<%= link_to 'Show', @cerveza %> |
<%= link_to 'Back', cervezas_path %>

app/views/cervezas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cervezas</h1>
<div class="jumbotron">
  <% if user_signed_in? %>
    <% @mis_pedidos.each do |pedido| %>
      <%= link_to image_tag(pedido.cerveza.photo_url, class:"pedido", size:"56x56"), cerveza_pedido_path(pedido.cerveza, pedido), method: :delete%>
    <% end %>
  <% end %>
</div>

<div class="container">
      <% @cervezas.each do |cerveza| %>
        <div class="col-md-3">
          <div class="thumbnail">
            <%= cerveza.nombre %>
            <%= cerveza.tipo %>
            <img src="<%= cerveza.photo_url %>" class="img-responsive">

            <div class="buttons">
              <%= link_to 'Show', cerveza, class:'btn' %>
              <!--<td><%= link_to 'Edit', edit_cerveza_path(cerveza) %></td>
              <td><%= link_to 'Destroy', cerveza, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
              <a href="<%= new_cerveza_pedido_path(cerveza) %>" class="btn btn-primary"> pedir </a>
            </div>
          </div>
        </div>
      <% end %>
  <br>

  <!--<%= link_to 'New Cerveza', new_cerveza_path %> -->
</div>

app/views/cervezas/new.html.erb
<h1>New Cerveza</h1>

<%= render 'form' %>

<%= link_to 'Back', cervezas_path %>

app/views/cervezas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cerveza.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @cerveza.tipo %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @cerveza.photo_url %>
</p>

<%= link_to 'Edit', edit_cerveza_path(@cerveza) %> |
<%= link_to 'Back', cervezas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EjemploClase</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/cervezas">Cervezas</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li >
          <% if user_signed_in? %>
            <%= link_to("Agregar Cervezas", new_cerveza_path ) %>
          <% else %>
            <%= link_to("Agregar Cervezas", new_user_session_path ) %>
          <% end %>
        </li>
        <li><a href="#">Mis Pedidos</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sesion<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% unless user_signed_in? %>

          		<li> <%= link_to("Ingresar", new_user_session_path)%></li>
          		<li> <%= link_to("Registrarse",  new_user_registration_path) %></li>
          	<% else %>
          		<li> <%= link_to("Salir",  destroy_user_session_path, method: :delete) %></li>
          	<% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/pedidos/_form.html.erb
<%= form_for(@pedido) do |f| %>
  <% if @pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
      <% @pedido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pedidos/edit.html.erb
<h1>Editing Pedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @pedido %> |
<%= link_to 'Back', pedidos_path %>

app/views/pedidos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pedidos</h1>

<table>
  <thead>
    <tr>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr>
        <td><%= pedido.cantidad %></td>
        <td><%= link_to 'Show', pedido %></td>
        <td><%= link_to 'Edit', edit_pedido_path(pedido) %></td>
        <td><%= link_to 'Destroy', pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pedido', new_pedido_path %>

app/views/pedidos/new.html.erb
<h1>New Pedido</h1>

<%= render 'form' %>

<%= link_to 'Back', pedidos_path %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cantidad:</strong>
  <%= @pedido.cantidad %>
</p>

<%= link_to 'Edit', edit_pedido_path(@pedido) %> |
<%= link_to 'Back', pedidos_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>